# Generated by Django 4.2 on 2024-11-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_category_watch_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='user',
            new_name='seller',
        ),
    ]
