# Generated by Django 4.2 on 2024-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_alter_category_options_rename_user_watch_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
