# Generated by Django 4.2 on 2024-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_watch_watch_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='marka',
            new_name='brand',
        ),
    ]
