# Generated by Django 4.2 on 2024-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_alter_watch_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='discount_dedline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
